services:
  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-ai-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./app:/app/app  # Mount for hot reload in development
    networks:
      - travel-ai-network
    restart: unless-stopped

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: travel-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - travel-ai-network
    restart: unless-stopped

  # Celery Worker (Background Jobs)
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-ai-celery-worker
    command: celery -A app.background.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    volumes:
      - ./app:/app/app
    networks:
      - travel-ai-network
    restart: unless-stopped

  # Celery Beat (Scheduled Tasks)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: travel-ai-celery-beat
    command: celery -A app.background.celery_app beat --loglevel=info
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    volumes:
      - ./app:/app/app
    networks:
      - travel-ai-network
    restart: unless-stopped

networks:
  travel-ai-network:
    driver: bridge

volumes:
  redis_data:
